name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.3.0

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2
  pointer_interceptor: ^0.9.3+3
  uuid: ^3.0.7
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
